<?php
	$countriesasia = array
		(
		"AFGHANISTAN",
		"ARMENIA",
		"AZERBAIJAN",
		"BAHRAIN",
		"BANGLADESH",
		"BRUNEI",
		"CAMBODIA",
		"CHINA",
		"CYPRUS",
		"GEORGIA",
		"INDIA",
		"INDONESIA",
		"IRAN",
		"IRAQ",
		"ISRAEL",
		"JAPAN",
		"JORDAN",
		"KAZAKHSTAN",
		"KUWAIT",
		"KYRGYZSTAN",
		"LAOS",
		"LEBANON",
		"MALAYSIA",
		"MALDIVES",
		"MONGOLIA",
		"NORTH KOREA",
		"OMAN",
		"PAKISTAN",
		"PHILIPPINES",
		"QATAR",
		"RUSSIA",
		"SAUDI ARABIA",
		"SINGAPORE",
		"SOUTH KOREA",
		"SRI LANKA",
		"SYRIA",
		"TAIWAN",
		"TAJIKISTAN",
		"THAILAND",
		"TURKEY",
		"TURKMENISTAN",
		"UNITED ARAB EMIRATES",
		"UZBEKISTAN",
		"VIETNAM",
		"YEMEN"
		);
?>