<?php
$countries = array(
        "AFGHANISTAN",
        "ARMENIA",
        "AZERBAIJAN",
        "BAHRAIN",
        "BANGLADESH",
        "BHUTAN",
        "BRUNEI",
        "CAMBODIA",
        "CHINA",
        "CYPRUS",
        "GEORGIA",
        "INDIA",
        "INDONESIA",
        "IRAN",
        "IRAQ",
        "ISRAEL",
        "JAPAN",
        "JORDAN",
        "KAZAKHSTAN",
        "KUWAIT",
        "KYRGYZSTAN",
        "LAOS",
        "LEBANON",
        "MALAYSIA",
        "MALDIVES",
        "MONGOLIA",
        "MYANMAR",
        "NEPAL",
        "NORTH KOREA",
        "OMAN",
        "PAKISTAN",
        "PALESTINE",
        "PHILIPPINES",
        "QATAR",
        "RUSSIA",
        "SAUDI ARABIA",
        "SINGAPORE",
        "SOUTH KOREA",
        "SRI LANKA",
        "SYRIA",
        "TAIWAN",
        "TAJIKISTAN",
        "THAILAND",
        "TIMOR-LESTE",
        "TURKEY",
        "TURKMENISTAN",
        "UNITED ARAB EMIRATES",
        "UZBEKISTAN",
        "VIETNAM",
        "YEMEN"
    );
    ?>